// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaouqvjikcgdeueoeftn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhb3Vxdmppa2NnZGV1ZW9lZnRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNzY2MzcsImV4cCI6MjA1NTc1MjYzN30.ntPWX8k5GUQK6UVMM9vTKLh2k0klJo-7uVPStttj0wU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);